wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684347690.072294
    t:
      1:
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.15.2
      8:
      - 1
      - 3
      - 5
    framework: torch
